var GAME_LEVELS = [
  ["                                                       ",
   "                                                       ",
   "                                                       ",
   "                                                       ",
   "                                                       ",
   "                                                       ",
   "                                                       ",
   "                                                       ",
   "                                                       ",
   "                                                       ",
   "                            o                          ",
   "                                                       ",
   "                            o                          ",
   "  x                        yyy                         ",
   "  x        oo      ypy                                 ",
   "  x       xxxx      e                                  ",
   "  x  @    x  x                   yyyyyyyyyyyyyyy       ",
   "  xxxxxxxxx  xxx                                       ",
   "               x    x                              o   ",
   "               x!!!!x   xxxx!!!!!!!!!x            yyy  ",
   "               x!!!!x      xxxxxxxxxxx                 ",
   "               xxxxxx                xx  s     y       ",
   "                                      xxxx             ",
   "                                                       "],
  ["                                                               ",
   "                                                               ",
   "                                                               ",
   "                                                               ",
   "                                                               ",
   "                                                               ",
   "                                                               ",
   "                                                               ",
   "                                                            s  ",
   "           xxx                                   o       yyyyy ",
   "          xx              yypy                  yyy            ",
   "         xx    yyy           e                                 ",
   "        xx           o                     yy         yy       ",
   "       xx           yyy                                        ",
   "      xx                        yyyyy                          ",
   "  @  xx                                  oo      yyy           ",
   " xxxxx                                  yyyy                   ",
   "                                                               ",
   "                                                               ",
   "                                                               "],
  ["                           v                                               ",
   "                                         xxx                               ",
   "                                        x!!!x                              ",
   "                                        x!!!x                              ",
   "    @                                   x!!!x                              ",
   "   xx       xxx                          xvx                               ",
   "    x      x!!!x                                  o                        ",
   "    x      x!!!x                                 yyyyp                     ",
   "    x       xvx                       o           e                   o    ",
   "    x                                                 !!!!!!xxxxxxxxxxx    ",
   "    x                                 o               !xxxxxx              ",
   "    x                                yyyyyyyyy        !           s        ",
   "    xxx   o           yyypy                           !           xxxxxxx  ",
   "      xxxxxxxxx             x                         !                    ",
   "              xxxx          x!!!!!!!!!!!!x     xxxx   !                    ",
   "                 x!!!!x     x!!!!!!!!!!!!x            !                    ",
   "                 x!!!!x     xxxxxxxxxxxxxx            !                    ",
   "                 x!!!!x                               !                    ",
   "                 x!!!!x           o           x       !                    ",
   "                 x!!!!x     =                =x       !                    ",
   "                 x!!!!xxxxxxxxxxxxxxxxxxxxxxxxx       !                    ",
   "                 xxxxxx                               !                    ",
   "                                                      !                    "],
  ["                                     ",
   "                                     ",
   "                                     ",
   "                                     ",
   "                                     ",
   "         o   o  oooo  o  o           ",
   "         o   o  o  o  o  o           ",
   "          ooo   o  o  o  o           ",
   "           o    o  o  o  o           ",
   "           o    oooo  oooo           ",
   "      xxxxxxxxxxxxxxxxxxxxxxx        ",
   "         o       o  o  oooo          ",
   "         o   o   o  o  o  o         s",
   "   xxx   o  o o  o  o  o  o          ",
   "x        o o   o o  o  o  o         x",
   "x        oo     oo  o  o  o         x",
   "x   @                               x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxpxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
